Web/ForumSystem.Web/Controllers/FeedbackController.cs
namespace ForumSystem.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Web.Mvc;
    using AutoMapper;
    using ForumSystem.Data.Common.Repository;
    using ForumSystem.Data.Models;
    using ForumSystem.Web.Infrastructure;
    using ForumSystem.Web.InputModels.Feedbacks;
    using Microsoft.AspNet.Identity;

    [ValidateInput(false)]
    public class FeedbackController : BaseController
    {
        public FeedbackController(IDeletableEntityRepository<Feedback> feedbacks, ISanitizer sanitizer) : base(feedbacks, sanitizer)
        {
        }

        // GET: Feedback
        public ActionResult Create()
        {
            var model = new PostFeedbackViewModel();
            return this.View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PostFeedbackViewModel input)
        {
            if (ModelState.IsValid)
            {
                var userId = this.User.Identity.GetUserId();

                var dbmodel = new Feedback()
                {
                    Title = input.Title,
                    Content = this.Sanitizer.Sanitize(input.Content),
                    AuthorId = userId
                };

                this.Feedbacks.Add(dbmodel);
                this.Feedbacks.SaveChanges();
                this.TempData["Success"] = "Feedback successfully send!";
                return this.RedirectToAction("Index", "Home");
            }

            return this.View(input);
        }
    }
}

Web/ForumSystem.Web/Controllers/PageableFeedbackListController.cs
namespace ForumSystem.Web.Controllers
{
    using System.Linq;
    using System.Web.Mvc;
    using AutoMapper.QueryableExtensions;
    using ForumSystem.Data.Common.Repository;
    using ForumSystem.Data.Models;
    using ForumSystem.Web.Infrastructure;
    using ForumSystem.Web.ViewModels.Feedbacks;
    using PagedList;

    [Authorize]
    public class PageableFeedbackListController : BaseController
    {
        private const int PageSize = 4;

        public PageableFeedbackListController(IDeletableEntityRepository<Feedback> feedbacks, ISanitizer sanitizer) : base(feedbacks, sanitizer)
        {
        }

         // GET: PageableFeedbackList
         ////[OutputCache(Duration=0)]
        [OutputCache(Duration = 15 * 60)]
        public ActionResult Display(int? page)
        {
            var feedback = Feedbacks.All()
                                    .Project()
                                    .To<FeedbackDisplayViewModel>()
                                    .OrderBy(f => f.CreatedOn);
            return this.View(feedback.ToPagedList(page ?? 1, PageSize));
        }
    }
}

Web/ForumSystem.Web/Controllers/QuestionsController.cs
namespace ForumSystem.Web.Controllers
{
    using System.Linq;
    using System.Web.Mvc;

    using AutoMapper.QueryableExtensions;

    using ForumSystem.Data.Common.Repository;
    using ForumSystem.Data.Models;
    using ForumSystem.Web.Infrastructure;
    using ForumSystem.Web.InputModels.Questions;
    using ForumSystem.Web.ViewModels.Questions;

    using Microsoft.AspNet.Identity;

    public class QuestionsController : Controller
    {
        private readonly IDeletableEntityRepository<Post> posts;

        private readonly ISanitizer sanitizer;

        public QuestionsController(IDeletableEntityRepository<Post> posts, ISanitizer sanitizer)
        {
            this.posts = posts;
            this.sanitizer = sanitizer;
        }

        // /questions/26864653/mysql-workbench-crash-on-start-on-windows
        public ActionResult Display(int id, string url, int page = 1)
        {
            var postViewModel = this.posts.All().Where(x => x.Id == id)
                .Project().To<QuestionDisplayViewModel>().FirstOrDefault();

            if (postViewModel == null)
            {
                return this.HttpNotFound("No such post");
            }

            return this.View(postViewModel);
        }

        // /questions/tagged/javascript
        public ActionResult GetByTag(string tag)
        {
            return this.Content(tag);
        }

        [HttpGet]
        [Authorize]
        public ActionResult Ask()
        {
            var model = new AskInputModel();
            return this.View(model);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Ask(AskInputModel input)
        {
            if (ModelState.IsValid)
            {
                var userId = this.User.Identity.GetUserId();

                var post = new Post
                    {
                        Title = input.Title,
                        Content = this.sanitizer.Sanitize(input.Content),
                        AuthorId = userId,
                        
                        // TODO: Tags
                        // TODO: Author
                    };

                this.posts.Add(post);
                this.posts.SaveChanges();
                return this.RedirectToAction("Display", new { id = post.Id, url = "new" });
            }

            return this.View(input);
        }
    }
}

Web/ForumSystem.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Forum System</title>
    @Styles.Render("~/Content/css")
    @RenderSection("styles", required: false)
</head>
<body>
    <div class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Forum System", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { })</li>
                    <li>@Html.ActionLink("Ask question", "Ask", "Questions", new { area = "" }, new { })</li>
                    <li>@Html.ActionLink("Send feedback", "Create", "Feedback", new { area = "" }, new { })</li>
                    <li>@Html.ActionLink("Feedbacks", "Display", "PageableFeedbackList", new { area = "" }, new { })</li>
                    @if (User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("Posts Administration", "Index", "PostsAdministration", new { area = "Administration" }, new { })</li>
                    }
                </ul>

                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        <ol class="breadcrumb">
            <li><a href="#">Home</a></li>
            <li><a href="#">Library</a></li>
            <li class="active">Data</li>
        </ol>
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - <a href="https://github.com/NikolayIT/ForumSystem">open source forum system</a></p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryval")
    @RenderSection("scripts", required: false)

</body>
</html>